<?php

declare(strict_types=1);

namespace App\Tools;

class Artisan extends ConsoleCommand
{
    public function vendorPublish(string $provider): void
    {
        $this->run("php artisan vendor:publish --provider='{$provider}'");
    }

    public function migrate()
    {
        $this->run('php artisan migrate');
    }

    public function runCustom(string $command): static
    {
        return $this->run("php artisan {$command}"); // TODO: Change the autogenerated stub
    }
}
